#!/usr/bin/env bash
set -euo pipefail

#######################################################################
# ASCII TOPOLOGY OVERVIEW
#######################################################################
#
#                  Root Namespace (switch dataplane)
#
#        +---------+      +---------+      +---------+      +---------+
#        | veth0   |      | veth1   |      | veth2   |      | veth3   |
#        +----+----+      +----+----+      +----+----+      +----+----+
#             |                |                |                |
#             |                |                |                |
#        +----+----+      +----+----+      +----+----+      +----+----+
#        | veth0p |      | veth1p |      | veth2p |      | veth3p |
#        +----+----+      +----+----+      +----+----+      +----+----+
#             |                |                |                |
#             |                |                |                |
#       +-----+-----+    +-----+-----+    +-----+-----+    +-----+-----+
#       |   h0      |    |   h1      |    |   h2      |    |   h3      |
#       +-----------+    +-----------+    +-----------+    +-----------+
#
#   Each host hX has interface vethXp with IP = 10.73.0.(X+1)/24
#   Switch-facing interfaces vethX remain in root namespace.
#
#######################################################################


#######################################################################
# Configuration constants
#######################################################################
NumPorts=4
BaseIP="10.73.0"   # results in 10.73.0.X
CSV_FILE="hostinfo.csv"
#######################################################################


#######################################################################
# 0. Cleanup
#######################################################################
cleanup() {
    echo "[*] Cleaning up old environment..."

    for ((i=0; i<NumPorts; i++)); do
        ip link del veth$i 2>/dev/null || true
        ip netns del h$i 2>/dev/null || true
    done

    rm -f "$CSV_FILE"

    echo "[+] Cleanup complete."
}


#######################################################################
# 1. Create namespaces
#######################################################################
create_namespaces() {
    echo "[*] Creating namespaces..."

    for ((i=0; i<NumPorts; i++)); do
        ip netns add h$i
        echo "    [+] Namespace h$i created"
    done

    echo "[+] Namespaces ready."
}


#######################################################################
# 2. Create veth pairs
#######################################################################
create_veth_pairs() {
    echo "[*] Creating veth pairs..."

    for ((i=0; i<NumPorts; i++)); do
        ip link add veth$i type veth peer name veth${i}p
        ip link set veth${i}p netns h$i
        echo "    [+] veth$i <-> veth${i}p created"
    done

    echo "[+] veth pairs created."
}


#######################################################################
# 3. Configure namespace interfaces
#######################################################################
configure_namespaces() {
    echo "[*] Configuring host interfaces..."

    > "$CSV_FILE"   # truncate/create CSV

    for ((i=0; i<NumPorts; i++)); do
        ns="h$i"
        iface="veth${i}p"
        ipaddr="${BaseIP}.$((i+1))"

        ip netns exec "$ns" ip link set lo up
        ip netns exec "$ns" ip addr add "${ipaddr}/24" dev "$iface"
        ip netns exec "$ns" ip link set "$iface" up

        # Extract MAC
        mac=$(ip netns exec "$ns" ip -o link show "$iface" | awk '{print $17}')

        echo "$ns,$iface,$ipaddr,$mac" >> "$CSV_FILE"

        echo "    [+] $ns: $iface IP=${ipaddr} MAC=${mac}"
    done

    echo "[+] Host interfaces configured."
    echo "[+] Hostinfo CSV written to: $CSV_FILE"
}


#######################################################################
# 4. Write uswitch config header
#######################################################################
write_uswitch_config() {
    echo "[*] Writing uswitch config header..."

    cat > src/switch_config.h <<EOF
// Generated by tools/$0
enum {
    NumSwitchPorts = ${NumPorts}
};
EOF

    echo "[+] uswitch_config.h written to ../uswitch/ with NumSwitchPorts=${NumPorts}"
}


#######################################################################
# 5. Bring up switch-facing ports in root namespace
#######################################################################
bring_up_switch_ports() {
    echo "[*] Bringing up veth interfaces for the switch..."

    for ((i=0; i<NumPorts; i++)); do
        ip link set veth$i up
        echo "    [+] veth$i UP"
    done

    echo "[+] Switch ports ready."
}


#######################################################################
# 6. MAC address viewer
#######################################################################
show_mac_addresses() {
    echo
    echo "========== MAC ADDRESS SUMMARY =========="

    echo
    echo "---- Switch-facing veth MACs ----"
    for ((i=0; i<NumPorts; i++)); do
        mac=$(ip -o link show veth$i | awk '{print $17}')
        echo "veth$i: $mac"
    done

    echo
    echo "---- Host-facing veth MACs ----"
    for ((i=0; i<NumPorts; i++)); do
        echo "h$i:"
        ip netns exec h$i ip -o link show veth${i}p
    done

    echo
    echo "========================================="
}


#######################################################################
# 7. Verification
#######################################################################
verify_environment() {
    echo
    echo "========== Verification =========="

    echo
    echo "---- Namespace Links ----"
    for ((i=0; i<NumPorts; i++)); do
        echo "h$i:"
        ip netns exec h$i ip -brief link
        echo
    done

    echo
    echo "---- Routing tables ----"
    for ((i=0; i<NumPorts; i++)); do
        echo "h$i:"
        ip netns exec h$i ip route
        echo
    done

    # echo
    # echo "---- Ping smoke test (expected FAIL, no switch yet) ----"
    # for ((i=0; i<NumPorts-1; i++)); do
    #     ip netns exec h$i ping -c1 -W1 ${BaseIP}.$((i+2)) || true
    # done

    show_mac_addresses

    echo
    echo "=================================="
    echo " Environment ready for uswitch."
    echo " Start switch with:"
    echo "      sudo ./uswitch"
    echo "=================================="
}


#######################################################################
# Main
#######################################################################
main() {
    cleanup
    create_namespaces
    create_veth_pairs
    configure_namespaces
    write_uswitch_config
    bring_up_switch_ports
    verify_environment
}

# Allow a single "cleanup" argument to only tear down the environment
case "${1:-}" in
    clean)
        cleanup
        ;;
    "")
        main
        ;;
    *)
        echo "Usage: $0 [clean]" >&2
        exit 1
        ;;
esac
